### ISSUE TITLE
Reference summaries for finetuning

### ISSUE THREAD

**Issue by OpUs-Nebula** [nsi319/Legal-Summarizer#2]
Hello, thanks for releasing this model to HuggingFace. What did you use as reference summaries when finetuning? The example text you summarize in the readme is a press release, which I would imagine is already a summary in itself. But I don't quite understand what you used as reference if the summaries of the press releases is what you finetuned for.

**Comment by nsi319** [comment]
Hi! The example text given in the README is a randomly picked litigation release. I just used it as an example to show how the model works since the original documents were large. The model was fine-tuned to generate the litigation releases from the complaints.

**Comment by OpUs-Nebula** [comment]
I see, thanks for clearing that up! How did you handle if multiple complaints existed?

**Comment by nsi319** [comment]
I used the latest complaint if multiple complaints existed.
